= Ansible

Ansible automates system administration tasks. In Ansible, **a play is a list of tasks to be executed on a set of hosts**. The tasks can be chosen from the available modules. One or several plays are organized in a playbook. 

The tasks in a play are executed sequentially. Handlers are tasks which are triggered by ”normal” tasks and are executed only once at the end of the play which triggered the handler.

The tasks are done by modules. You will learn how to use these modules, which arguments are required and which are optional to each module and how these modules are packed together to playbooks.

Ansible can be used in two methodes:

* the **ad hoc mode/method** by using individual modules
* the **playbook mode/method** by combining modules in one or more plays 

So a play is an ordered set of tasks executed against hosts. These managed or targeted hosts of the play can be on premise or in the cloud. All you need to be able to manage a system with Ansible, is ssh access.

== Study material

Read the introduction on Ansible on https://docs.ansible.com/ansible/latest/user_guide/quickstart.html[this] site. 

Watch the following videos from https://sysadmincasts.com:

* https://sysadmincasts.com/episodes/43-19-minutes-with-ansible-part-1-4[video 1]
* https://sysadmincasts.com/episodes/45-learning-ansible-with-vagrant-part-2-4[Video 2]

Do 1 to 5 in https://www.learnitguide.net/2018/06/ansible-tutorial-for-beginners-online.html[this text] and read to finish this https://linuxhint.com/ansible-tutorial-beginners/[text].

== Setting up the environment

* Make a Vagrant multimachine configuration with three machines: one master node named *master* (generic/freebsd12) and two slave nodes (generic/debian11) named *slave1* and *slave2*.


    Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
          v.memory = 512
          v.linked_clone = true
    end
    config.vm.define "master" do |master|
        master.vm.box = "swenr/debian"
        master.vm.hostname= "master"
    end
    config.vm.define "node1" do |node1|
        node1.vm.box = "swenr/debian"
        node1.vm.hostname= "node1"
    end
    config.vm.define "node2" do |node2|
        node2.vm.box = "swenr/debian"
        node2.vm.hostname= "node2"
    end
    end


* Install ansible on the master node

  $ sudo su - (you will be prompted for the root password, normally vagrant)
  # apt update
  # apt install ansible sshpass

* Verify if ansible is installed

  $ ansible --version
  $ ansible-playbook --version

* You need to specify an inventory of hosts, ansible will use to run ad-hoc commands or playbooks on. The inventory file can contain the DNS names or the IP addresses of the hosts. Because DNS is not configured in this exercise, IP addresses will be used
** Modify your Vagrant file so the master machine has IP 10.10.10.10, node1 has IP 10.10.10.20 and node2 has IP 10.10.10.21.

    Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.linked_clone = true
    end
    config.vm.define "master" do |master|
        master.vm.box = "swenr/debian"
        master.vm.hostname= "master"
        master.vm.network "private_network", ip: "10.10.10.10"
    end
    config.vm.define "node1" do |node1|
        node1.vm.box = "swenr/debian"
        node1.vm.hostname= "node1"
        node1.vm.network "private_network", ip: "10.10.10.20"
    end
    config.vm.define "node2" do |node2|
        node2.vm.box = "swenr/debian"
        node2.vm.hostname= "node2"
        node2.vm.network "private_network", ip: "10.10.10.21"
    end



* Make a subdirectory *ansible* on the master node and create a file *inventory* within the newly created directory
  
  $ cd /home/vagrant
  $ mkdir ansible
  $ cd ansible
  $ touch inventory

* Read the https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups[documentation] on Ansible inventory files and create a static inventory file in YAML format containing the IP addresses of the three machines

  all:
    hosts:
      10.10.10.10:
    children:
      nodes:
        hosts:
          10.10.10.20:
          10.10.10.21:

** Verify the listed hosts
  
  $ ansible --list-hosts -i inventory all
  $ ansible --list-hosts -i inventory ungrouped
  $ ansible --list-hosts -i inventory nodes
  $ ansible --list-hosts -i inventory nodes,ungrouped
  $ ansible-inventory -i inventory --list

* Start by reading the default help output when you run the command `ansible help`.

* Use ssh to connect to the two node1 and node2 machines in order to verify the ssh connection is working (Type **yes** to continue if SSH asks you something)
** When the ssh connection to the node machines works, you can safely close the ssh connection and continue. If this connection is not working => troubleshoot.  

* Use the ping-module to "ping" the hosts using the following command: `ansible -i inventory nodes -m ping --ask-pass`
** Use the man pages of the ansible command "to figure the command out"

* Switch in the previous command the ping module with the setup module and read the output

== Ansible ad hoc commands

Ad hoc commands are one-liners designed to achieve a very specific task. To put simply, Ansible ad hoc commands are one-liner Linux shell commands and playbooks are like a shell script, a collective of many commands with logic.

Ansible ad hoc commands come in handy when you want to perform a quick task.

Modules do the ”real” work in Ansible. Ansible contains a lot of modules by default, but you can also write your own.mode

The default syntax for using an Ansible module in an *ad hoc command* is: `ansible -i inventory-file host-group -m module-name -a module-arguments`

For example:
  
  ansible -i inventroy-file webservers -m <modulename> -a <arguments to the module>


If you don’t know how to use the module or which arguments are optional or required, you can use the command `ansible-doc -l` for an overview of all available modules on the system and `ansible-doc *module-name*` for specific module details.

* Write an ansible ad hoc command to check the uptime on node 1 and 2

    ansible -k -i inventory nodes -m shell -a uptime

* Sometimes it is necessary to become "root" during the installation or configuration of the system. Execute the following commands and explain their working:

  ansible -k -i inventory nodes -m shell -a id
  ansible -k -b -i inventory nodes -m shell -a id
  ansible -k -b -K -i inventory nodes -m shell -a id

* Create a UNIX user using the ansible *user module*

  ansible -k -b -K -i inventory nodes -m user -a "name=student1 createhome=yes"

  * You can obtain a list of available modules using `ansible-doc -l`
  ** How many modules are include? 

  * Use ansible-doc to figure out how to use the copy module: `ansible-doc copy`

* Try the following commands:

  `ansible -k -i inventory nodes -m command -a ’echo "JAJA" >> /tmp/JAJA’`
  `ansible -k -i inventory nodes -m shell -a ’echo "JAJA" >> /tmp/JAJA’`
  
** Explain and TEST the difference in behavior between the two commands.
*** Tip: https://blog.confirm.ch/ansible-modules-shell-vs-command/

* Execute the following command `ansible -i inventory nodes -m copy -a 'src=/etc/passwd dest=/tmp/passwd' -k` twice.
** Do you see a difference in the ansible outcome?
*** "changed": ...

* Use the appropriate package management module to reassure that the latest openssl version is present on the node systems

 ansible -k -b -K -i inventory nodes -m package -a 'name=openssl state=latest'

* Find out how to use the file module to create a file *kroepoek* in the folder /tmp


.NOTE
  Modules are ‘idempotent’, they will make only the changes they must in order to bring the system to the desired state. This makes it very safe to rerun the same modules (and playbook) multiple times. They won’t change things unless they have to change things.

  The *command* and *shell* modules will typically rerun the same command again, which is totally ok if the command is something like chmod or chown, etc. Though there is a creates flag available which can be used to make also these modules idempotent. Test these modules with the create flag and make them ‘idempotent’ in your use. 

// ansible -i inventory.yml nodes -m shell -a 'id creates=/tmp'  -k -b

== Ansible Playbooks

Another way to run Ansible is by using Playbooks, in playbook mode. A playbook by itself is a plain-text YAML file that describes the desired *end state*. 

**Playbooks contain plays, plays contain tasks and tasks call one or more modules.**

At the end of a play the actions (tasks) in the handler are executed if they were called upon or triggered by via notify.

Here is an example of an Ansible playbook which contains just one play. Note that it has to start with three dash (-) signs!

  −−−
  − name: My First Play
    hosts: webservers
    tasks:
    − name: ensure apache is at the latest version
      package: 
        name=httpd state=latest
    − name: write the apache config file
      copy:
        src=/srv/httpd.conf dest=/etc/httpd.conf
      notify:
      − restart apache
    − name: ensure apache is running (and enable it at boot)
      service:
        name=httpd
        state=started
        enabled=yes
     handlers:
     − name: restart apache
       service:
         name=httpd
         state=restarted

As you can see, playbooks are almost self explanatory. This one play playbook starts with the name of the play and the hosts or inventory group to which to apply the play. Next, it lists all tasks to be performed. The last part contains the handlers.

---
How do you create a playbook?

* Begin by creating an ad hoc command for each installation or configuration action.
* Bring those ad hoc commands together into one or more plays    

---

Plays, like tasks, run in the order specified in the playbook: top to bottom. Each tasks is given a name and followed by one or more modules that are doing the real ”work".
An Ansible playbook is run via the command: `ansible-playbook <options> playbook-name`.

Read this https://www.ansible.com/blog/getting-started-writing-your-first-playbook[text] and be sure you know what a playbook is. Otherwise "Google is your friend"

* Write your first playbook named playbook.yml containing:
** one play with name "Play1"
** as target the host group "nodes"
** One task named "Ping" using the ping module

    ---
    - name: Play1
      hosts: nodes
      tasks:
      - name: Ping
        ping:

* Extend your playbook with another, play Play2 which installs nginx on the host group **nodes**.

    ---
    - name: Play1
      hosts: nodes
      tasks:
      - name: Ping
        ping:
    - name: Play2
      hosts: nodes
      become: yes
      tasks:
      - name: Install nginx
        apt:
          name: nginx
          update_cache: yes
          state: present
      - name: Start service nginx, if not started
        service:
          name: nginx
          state: started

* Explain the statement "become: yes" in previous playbook. 

* Run the playbook: `ansible-playbook -k -K -i inventory playbook.yml`
** What happens when you enable the -v, -vv or -vvv flags?

== Exercises
=== Exercises 1

Create a playbook that installs and configures a Tomcat server on the **nodes** host group. Read the playbook and explain the different tasks containing it. Reference to the vagrant.zip file. 


    ---
    - hosts: nodes
      gather_facts: no
      tasks:
      - name: Test connection
        ping:
      - name: Update Apt sources
        become: yes
        apt:
          update_cache: yes
          upgrade: yes
          autoremove: yes
      - name: Install JDK
        become: yes
        apt:
          name: openjdk-17-jre
          state: latest
      - name: Check Java version
        shell: java -version
        register: java_version
        failed_when: not java_version.stderr.startswith('openjdk version \"17.')
      - name: Create tomcat group
        become: yes
        group:
          name: tomcat
          state: present
      - name: Create tomcat user
        become: yes
        user:
          name: tomcat
          group: tomcat
          home: /home/tomcat
          shell: /bin/false
          state: present
      - name: Copy latest Tomcat
        ansible.builtin.copy:
          src: "/tmp/apache-tomcat-10.0.17.tar.gz"
          dest: "/tmp/apache-tomcat-10.0.17.tar.gz"
      - name: Extract Tomcat
        become: yes
        unarchive:
          src: "/tmp/apache-tomcat-10.0.17.tar.gz"
          remote_src: yes
          dest: "/opt/tomcat10"
          creates: "/opt/tomcat10/conf"
          extra_opts: [--strip-components=1]
      - name: Make tomcat owner of /opt/tomcat10
        become: yes
        file:
          path: "/opt/tomcat10"
          state: directory
          mode: "u=rwx,g=rx,o=rx"
          owner: tomcat
          group: tomcat
          recurse: yes
      - name: Add ADMIN-WEB user to tomcat-users.xml
        become: yes
        lineinfile:
          path: /opt/tomcat10/conf/tomcat-users.xml
          line: '<role rolename="manager-gui"/> <user name="admin" password="VerySecurePasswd" roles="manager-gui"/>'
          insertbefore: "</tomcat-users>"
      - name: Allow remote access to manager GUI
        become: yes
        replace:
            path: "/opt/tomcat10/webapps/manager/META-INF/context.xml"
            regexp: allow="127.+\:1"
            replace: allow=".*"
      - name: Copy tomcat service
        become: yes
        copy:
          src: /tmp/tomcat.service
          dest: /etc/systemd/system/tomcat.service
      - name: enable tomcat startup
        become: yes
        systemd:
          name: tomcat
          enabled: yes
          state: restarted

== Exercise 2
Read https://www.unixtutorial.org/skip-gathering-facts-in-ansible/[this] and modify the playbook of exercise 1.

== Exercise 3: Available Ansible Provisioners

Vagrant supports two different Ansible provisioners:

* ansible - the regular Ansible provisioner, requires the Ansible executable to
be available on the Host machine. This provisioner will execute Ansible on the
Host machine, to provision the Guest. We are going to use this provisioner for
the examples in this book.

* ansible_local - runs locally inside the Guest machine. The advantage of using
ansible_local is that it doesn’t require Ansible to be installed on the Host
machine in order to run.

=== The Vagrantfile

We need to define the Ansible provisioner in our Vagrantfile, with the config.vm.provision method call.
This is a basic example, where we just set the location of the playbook file :
    
    Vagrant.configure("2") do |config|
      config.vm.box = "debian/bullseye64"
      config.vm.hostname = "nextcloud"
      config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
      config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "nextcloud_playbook1.yml"
    #    ansible.playbook = "nextcloud_playbook2.yml"
    #    ansible.playbook = "nextcloud_playbook3.yml"
    #    ansible.verbose = 'vvv' #accepted values: from 'v' to 'vvvv
      end
    end

=== The Playbook
The playbook is where we’re going to define our tasks. A playbook containing the “Install Nginx” task, plus php7.0-fpm installation, would look like
this:

    ---
    - hosts: all
      become: yes
      tasks:
      - name: Install Nginx
        apt: name=nginx
      - name: Install php7.0-fpm
        apt: name=php7.0-fpm

This Playbook tells Ansible to run the defined tasks on *all* inventory hosts. 
The inventory file defines the machines Ansible will control; with Vagrant, usually you will be working with a single machine, and the inventory file is automatically generated by Vagrant, under the path .vagrant/provisioners/ansible/inventory.


Watch following https://www.youtube.com/watch?v=2OsNGj2n2zc[youtube] and create three playbooks to install *Nextcloud*. It is not possible to automate everything.  

== Sources
* https://www.ansible.com/quick-start-video
* https://docs.ansible.com/ansible/playbooks.html
* https://www.ansible.com/webinars-training
* https://serversforhackers.com/an-ansible-tutorial
